export const API = {
  USER: {
    LOGIN: '/api/login',
    LOGOUT: '/api/logout',
    REFRESH: '/api/refresh',
    CLUBS: '/api/clubs',
    POPULAR_CLUBS: '/api/clubs/banner/popular',
    SEARCH: '/api/clubs/search',
    FAVORITES_TOGGLE: (clubId: string) => `/api/favorites/toggle/${clubId}`,
    GOOGLE_LOGIN: '/api/user/auth/oauth/google',
    GOOGLE_ONBOARDING: '/api/user/auth/oauth/google/complete',
    CLUB_BOARDS: (clubId: string) => `/api/clubs/${clubId}/boards`,
    CLUB_BOARD_DETAIL: (clubId: string, boardId: string) =>
      `/api/clubs/${clubId}/boards/${boardId}`,
  },
  ADMIN: {
    LOGIN: '/auth/login',
    SIGNUP: '/auth/join',
    PASSWORD: '/auth/reset-password',
    LOGOUT: '/auth/logout',
    RE_ISSUE: '/auth/re-issue',
    APPLICANTS: '/applies',
    APPLICANTS_PASS: '/applies/passed',
    APPLICANTS_FAIL: '/applies/failed',
    APPLICANTS_SEARCH: '/applies/search',
    APPLICANTS_STATUS: (applicantId: string) => `/applies/evaluations/${applicantId}`,
    APPLICANTS_DETAIL: (applicantId: string) => `/applies/${applicantId}`,
    APPLICANTS_MEMO_CREATE: (applicantId: string) => `/applies/${applicantId}/memos`,
    APPLICANTS_MEMO_DELETE: (applicantId: string, memoId: string) =>
      `/applies/${applicantId}/memos/${memoId}`,
    APPLICANTS_MEMO_UPDATE: (applicantId: string, memoId: string) =>
      `/applies/${applicantId}/memos/${memoId}`,
    FORMS: (clubId: string) => `/forms/${clubId}`,
    FORMS_UPDATE: (formId: string) => `/forms/${formId}`,
    FORMS_FINISH: (formId: string) => `/forms/finish/${formId}`,
    APPLICANTS_CONNECTION: (clubId: string) => `/applies/${clubId}/finalize`,
    FORMS_CREATE: (clubId: string) => `/forms/clubs/${clubId}`,
    CLUB_BOARDS: (clubId: string) => `/clubs/${clubId}/boards`,
    CLUB_BOARD_DETAIL: (clubId: string, boardId: string) => `/clubs/${clubId}/boards/${boardId}`,
  },
};
