import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../common/styles/reset.css.ts';
import { MSWProvider } from '@/mocks/mswProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${pretendard.variable}`}>
      <head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'
        />
      </head>
      <body>
        <MSWProvider>{children}</MSWProvider>
      </body>
    </html>
  );
}
