export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  PASSWORD: '/password',
  POPULAR: '/popular',
  FAVORITES: '/favorites?sort=latest',
  APPLIED: '/applied?sort=latest',
  CLUB_INFO: (clubId: number) => `/club/${clubId}`,
  ADMIN: '/admin',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_APPLICATIONS: '/admin/applicants?evaluation=applies&sort=grade',
  ADMIN_CLUB_MEMBER: '/admin/clubMember',
  ADMIN_APPLICATIONS_FORM: '/admin/applicationsForm',
  ADMIN_APPLICATIONS_CREATE: '/admin/createForm',
  ADMIN_APPLICATIONS_MESSAGE: '/admin/applicants/message',
};
