export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  PASSWORD: '/password',
  POPULAR: '/popular',
  FAVORITES: '/favorites',
  APPLIED: '/applied',
  SEARCH: (name: string) => `/search?name=${name}`,
  CLUB_INFO: (clubId: number) => `/club/${clubId}`,
  APPLIY_FORM: (clubId: number) => `/club/${clubId}/apply`,
  ADMIN: '/admin',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_APPLICATIONS: '/admin/applicants?evaluation=applies&sort=grade',
  ADMIN_CLUB_MEMBER: '/admin/clubMember',
  ADMIN_APPLICATIONS_FORM: '/admin/applicationsForm',
  ADMIN_APPLICATIONS_CREATE: '/admin/createForm',
  ADMIN_APPLICATIONS_MESSAGE: '/admin/applicants/message',
};
